// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_delivery_app/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:convert' as _i41;
import 'dart:typed_data' as _i42;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_delivery_app/core/error/failures.dart' as _i11;
import 'package:flutter_delivery_app/core/usecases/usecase.dart' as _i20;
import 'package:flutter_delivery_app/data/data_sources/local/delivery_info_local_data_source.dart'
    as _i27;
import 'package:flutter_delivery_app/data/data_sources/local/schedule_local_data_source.dart'
    as _i31;
import 'package:flutter_delivery_app/data/data_sources/local/service_local_data_source.dart'
    as _i14;
import 'package:flutter_delivery_app/data/data_sources/local/user_local_data_source.dart'
    as _i24;
import 'package:flutter_delivery_app/data/data_sources/remote/delivery_info_remote_data_source.dart'
    as _i28;
import 'package:flutter_delivery_app/data/data_sources/remote/driver_remote_data_source.dart'
    as _i35;
import 'package:flutter_delivery_app/data/data_sources/remote/rating_remote_data_source.dart'
    as _i39;
import 'package:flutter_delivery_app/data/data_sources/remote/schedule_remote_data_source.dart'
    as _i32;
import 'package:flutter_delivery_app/data/data_sources/remote/service_remote_data_source.dart'
    as _i15;
import 'package:flutter_delivery_app/data/data_sources/remote/user_remote_data_source.dart'
    as _i23;
import 'package:flutter_delivery_app/data/models/delivery/delivery_info_model.dart'
    as _i6;
import 'package:flutter_delivery_app/data/models/driver/driver_model.dart'
    as _i36;
import 'package:flutter_delivery_app/data/models/rating/rating_model.dart'
    as _i40;
import 'package:flutter_delivery_app/data/models/schedule/schedule_model.dart'
    as _i7;
import 'package:flutter_delivery_app/data/models/service/service_response_model.dart'
    as _i3;
import 'package:flutter_delivery_app/data/models/user/authentication_response_model.dart'
    as _i5;
import 'package:flutter_delivery_app/data/models/user/user_model.dart' as _i4;
import 'package:flutter_delivery_app/domain/entities/delivery/delivery_info.dart'
    as _i26;
import 'package:flutter_delivery_app/domain/entities/driver/driver.dart'
    as _i34;
import 'package:flutter_delivery_app/domain/entities/rating/rating.dart'
    as _i38;
import 'package:flutter_delivery_app/domain/entities/schedule/schedule.dart'
    as _i30;
import 'package:flutter_delivery_app/domain/entities/service/service_response.dart'
    as _i12;
import 'package:flutter_delivery_app/domain/entities/user/user.dart' as _i17;
import 'package:flutter_delivery_app/domain/repositories/delivery/delivery_info_repository.dart'
    as _i25;
import 'package:flutter_delivery_app/domain/repositories/driver/driver_repository.dart'
    as _i33;
import 'package:flutter_delivery_app/domain/repositories/rating/rating_repository.dart'
    as _i37;
import 'package:flutter_delivery_app/domain/repositories/schedule/schedule_repository.dart'
    as _i29;
import 'package:flutter_delivery_app/domain/repositories/service/service_repository.dart'
    as _i9;
import 'package:flutter_delivery_app/domain/repositories/user/user_repository.dart'
    as _i16;
import 'package:flutter_delivery_app/domain/usecases/service/get_service_use_case.dart'
    as _i13;
import 'package:flutter_delivery_app/domain/usecases/user/login_use_case.dart'
    as _i19;
import 'package:flutter_delivery_app/domain/usecases/user/register_use_case.dart'
    as _i18;
import 'package:hive/hive.dart' as _i21;
import 'package:http/http.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceResponseModel_1 extends _i1.SmartFake
    implements _i3.ServiceResponseModel {
  _FakeServiceResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_2 extends _i1.SmartFake implements _i4.UserModel {
  _FakeUserModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthenticationResponseModel_3 extends _i1.SmartFake
    implements _i5.AuthenticationResponseModel {
  _FakeAuthenticationResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeliveryInfoModel_4 extends _i1.SmartFake
    implements _i6.DeliveryInfoModel {
  _FakeDeliveryInfoModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScheduleModel_5 extends _i1.SmartFake implements _i7.ScheduleModel {
  _FakeScheduleModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_7 extends _i1.SmartFake
    implements _i8.StreamedResponse {
  _FakeStreamedResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceRepository extends _i1.Mock implements _i9.ServiceRepository {
  MockServiceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i12.ServiceResponse>> getRemoteServices(
          _i13.FilterServiceParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteServices,
          [params],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i12.ServiceResponse>>.value(
                _FakeEither_0<_i11.Failure, _i12.ServiceResponse>(
          this,
          Invocation.method(
            #getRemoteServices,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i12.ServiceResponse>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i12.ServiceResponse>> getLocalServices(
          _i13.FilterServiceParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalServices,
          [params],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i12.ServiceResponse>>.value(
                _FakeEither_0<_i11.Failure, _i12.ServiceResponse>(
          this,
          Invocation.method(
            #getLocalServices,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i12.ServiceResponse>>);
}

/// A class which mocks [ServiceLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceLocalDataSource extends _i1.Mock
    implements _i14.ServiceLocalDataSource {
  MockServiceLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> cacheServices(_i3.ServiceResponseModel? servicesToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheServices,
          [servicesToCache],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.ServiceResponseModel> getCachedServices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedServices,
          [],
        ),
        returnValue: _i10.Future<_i3.ServiceResponseModel>.value(
            _FakeServiceResponseModel_1(
          this,
          Invocation.method(
            #getCachedServices,
            [],
          ),
        )),
      ) as _i10.Future<_i3.ServiceResponseModel>);
}

/// A class which mocks [ServiceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceRemoteDataSource extends _i1.Mock
    implements _i15.ServiceRemoteDataSource {
  MockServiceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i3.ServiceResponseModel> getServices(
          _i13.FilterServiceParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServices,
          [params],
        ),
        returnValue: _i10.Future<_i3.ServiceResponseModel>.value(
            _FakeServiceResponseModel_1(
          this,
          Invocation.method(
            #getServices,
            [params],
          ),
        )),
      ) as _i10.Future<_i3.ServiceResponseModel>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i16.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i17.User>> registerUser(
          _i18.RegisterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [params],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i17.User>>.value(
            _FakeEither_0<_i11.Failure, _i17.User>(
          this,
          Invocation.method(
            #registerUser,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i17.User>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i17.User>> loginUser(
          _i19.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [params],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i17.User>>.value(
            _FakeEither_0<_i11.Failure, _i17.User>(
          this,
          Invocation.method(
            #loginUser,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i17.User>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i20.NoParams>> logoutUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutUser,
          [],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i20.NoParams>>.value(
            _FakeEither_0<_i11.Failure, _i20.NoParams>(
          this,
          Invocation.method(
            #logoutUser,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i20.NoParams>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i17.User>> getLocalUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalUser,
          [],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i17.User>>.value(
            _FakeEither_0<_i11.Failure, _i17.User>(
          this,
          Invocation.method(
            #getLocalUser,
            [],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i17.User>>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i21.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i10.Stream<_i21.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i10.Stream<_i21.BoxEvent>.empty(),
      ) as _i10.Stream<_i21.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i10.Future<Iterable<int>>.value(<int>[]),
      ) as _i10.Future<Iterable<int>>);

  @override
  _i10.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i23.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.UserModel> registerUser(_i18.RegisterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [params],
        ),
        returnValue: _i10.Future<_i4.UserModel>.value(_FakeUserModel_2(
          this,
          Invocation.method(
            #registerUser,
            [params],
          ),
        )),
      ) as _i10.Future<_i4.UserModel>);

  @override
  _i10.Future<_i5.AuthenticationResponseModel> loginUser(
          _i19.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [params],
        ),
        returnValue: _i10.Future<_i5.AuthenticationResponseModel>.value(
            _FakeAuthenticationResponseModel_3(
          this,
          Invocation.method(
            #loginUser,
            [params],
          ),
        )),
      ) as _i10.Future<_i5.AuthenticationResponseModel>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i24.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #getToken,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i10.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #getUserId,
            [],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i4.UserModel> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i10.Future<_i4.UserModel>.value(_FakeUserModel_2(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
      ) as _i10.Future<_i4.UserModel>);

  @override
  _i10.Future<void> saveUser(_i4.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isTokenAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isTokenAvailable,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}

/// A class which mocks [DeliveryInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryInfoRepository extends _i1.Mock
    implements _i25.DeliveryInfoRepository {
  MockDeliveryInfoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i26.DeliveryInfo>>>
      getRemoteDeliveryInfo() => (super.noSuchMethod(
            Invocation.method(
              #getRemoteDeliveryInfo,
              [],
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.Failure, List<_i26.DeliveryInfo>>>.value(
                _FakeEither_0<_i11.Failure, List<_i26.DeliveryInfo>>(
              this,
              Invocation.method(
                #getRemoteDeliveryInfo,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i26.DeliveryInfo>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i26.DeliveryInfo>>>
      getLocalDeliveryInfo() => (super.noSuchMethod(
            Invocation.method(
              #getLocalDeliveryInfo,
              [],
            ),
            returnValue: _i10.Future<
                    _i2.Either<_i11.Failure, List<_i26.DeliveryInfo>>>.value(
                _FakeEither_0<_i11.Failure, List<_i26.DeliveryInfo>>(
              this,
              Invocation.method(
                #getLocalDeliveryInfo,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, List<_i26.DeliveryInfo>>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>> addDeliveryInfo(
          _i6.DeliveryInfoModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDeliveryInfo,
          [params],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>.value(
                _FakeEither_0<_i11.Failure, _i26.DeliveryInfo>(
          this,
          Invocation.method(
            #addDeliveryInfo,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>> editDeliveryInfo(
          _i6.DeliveryInfoModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #editDeliveryInfo,
          [params],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>.value(
                _FakeEither_0<_i11.Failure, _i26.DeliveryInfo>(
          this,
          Invocation.method(
            #editDeliveryInfo,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>> selectDeliveryInfo(
          _i26.DeliveryInfo? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectDeliveryInfo,
          [params],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>.value(
                _FakeEither_0<_i11.Failure, _i26.DeliveryInfo>(
          this,
          Invocation.method(
            #selectDeliveryInfo,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>
      getSelectedDeliveryInfo() => (super.noSuchMethod(
            Invocation.method(
              #getSelectedDeliveryInfo,
              [],
            ),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>.value(
                    _FakeEither_0<_i11.Failure, _i26.DeliveryInfo>(
              this,
              Invocation.method(
                #getSelectedDeliveryInfo,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, _i26.DeliveryInfo>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i20.NoParams>>
      deleteLocalDeliveryInfo() => (super.noSuchMethod(
            Invocation.method(
              #deleteLocalDeliveryInfo,
              [],
            ),
            returnValue:
                _i10.Future<_i2.Either<_i11.Failure, _i20.NoParams>>.value(
                    _FakeEither_0<_i11.Failure, _i20.NoParams>(
              this,
              Invocation.method(
                #deleteLocalDeliveryInfo,
                [],
              ),
            )),
          ) as _i10.Future<_i2.Either<_i11.Failure, _i20.NoParams>>);
}

/// A class which mocks [DeliveryInfoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryInfoLocalDataSource extends _i1.Mock
    implements _i27.DeliveryInfoLocalDataSource {
  MockDeliveryInfoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i6.DeliveryInfoModel>> getDeliveryInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryInfo,
          [],
        ),
        returnValue: _i10.Future<List<_i6.DeliveryInfoModel>>.value(
            <_i6.DeliveryInfoModel>[]),
      ) as _i10.Future<List<_i6.DeliveryInfoModel>>);

  @override
  _i10.Future<_i6.DeliveryInfoModel?> getSelectedDeliveryInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedDeliveryInfo,
          [],
        ),
        returnValue: _i10.Future<_i6.DeliveryInfoModel?>.value(),
      ) as _i10.Future<_i6.DeliveryInfoModel?>);

  @override
  _i10.Future<void> saveDeliveryInfo(List<_i6.DeliveryInfoModel>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDeliveryInfo,
          [params],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateDeliveryInfo(_i6.DeliveryInfoModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDeliveryInfo,
          [params],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateSelectedDeliveryInfo(_i6.DeliveryInfoModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSelectedDeliveryInfo,
          [params],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearDeliveryInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearDeliveryInfo,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [DeliveryInfoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryInfoRemoteDataSource extends _i1.Mock
    implements _i28.DeliveryInfoRemoteDataSource {
  MockDeliveryInfoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i6.DeliveryInfoModel>> getDeliveryInfo(
    String? token,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryInfo,
          [
            token,
            userId,
          ],
        ),
        returnValue: _i10.Future<List<_i6.DeliveryInfoModel>>.value(
            <_i6.DeliveryInfoModel>[]),
      ) as _i10.Future<List<_i6.DeliveryInfoModel>>);

  @override
  _i10.Future<_i6.DeliveryInfoModel> addDeliveryInfo(
    _i6.DeliveryInfoModel? params,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDeliveryInfo,
          [
            params,
            token,
          ],
        ),
        returnValue:
            _i10.Future<_i6.DeliveryInfoModel>.value(_FakeDeliveryInfoModel_4(
          this,
          Invocation.method(
            #addDeliveryInfo,
            [
              params,
              token,
            ],
          ),
        )),
      ) as _i10.Future<_i6.DeliveryInfoModel>);

  @override
  _i10.Future<_i6.DeliveryInfoModel> editDeliveryInfo(
    _i6.DeliveryInfoModel? params,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editDeliveryInfo,
          [
            params,
            token,
          ],
        ),
        returnValue:
            _i10.Future<_i6.DeliveryInfoModel>.value(_FakeDeliveryInfoModel_4(
          this,
          Invocation.method(
            #editDeliveryInfo,
            [
              params,
              token,
            ],
          ),
        )),
      ) as _i10.Future<_i6.DeliveryInfoModel>);
}

/// A class which mocks [ScheduleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleRepository extends _i1.Mock
    implements _i29.ScheduleRepository {
  MockScheduleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i30.Schedule>> bookSchedule(
          _i7.ScheduleModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookSchedule,
          [params],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i30.Schedule>>.value(
            _FakeEither_0<_i11.Failure, _i30.Schedule>(
          this,
          Invocation.method(
            #bookSchedule,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i30.Schedule>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, _i30.Schedule>> updateSchedule(
          _i7.ScheduleModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [params],
        ),
        returnValue: _i10.Future<_i2.Either<_i11.Failure, _i30.Schedule>>.value(
            _FakeEither_0<_i11.Failure, _i30.Schedule>(
          this,
          Invocation.method(
            #updateSchedule,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, _i30.Schedule>>);

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i30.Schedule>>> getSchedulesByUser(
          _i7.ScheduleModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSchedulesByUser,
          [params],
        ),
        returnValue:
            _i10.Future<_i2.Either<_i11.Failure, List<_i30.Schedule>>>.value(
                _FakeEither_0<_i11.Failure, List<_i30.Schedule>>(
          this,
          Invocation.method(
            #getSchedulesByUser,
            [params],
          ),
        )),
      ) as _i10.Future<_i2.Either<_i11.Failure, List<_i30.Schedule>>>);
}

/// A class which mocks [ScheduleLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleLocalDataSource extends _i1.Mock
    implements _i31.ScheduleLocalDataSource {
  MockScheduleLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> cacheSchedule(List<_i7.ScheduleModel>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheSchedule,
          [params],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateSchedule(_i7.ScheduleModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [params],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i7.ScheduleModel>> getSchedulesByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSchedulesByUser,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i7.ScheduleModel>>.value(<_i7.ScheduleModel>[]),
      ) as _i10.Future<List<_i7.ScheduleModel>>);
}

/// A class which mocks [ScheduleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleRemoteDataSource extends _i1.Mock
    implements _i32.ScheduleRemoteDataSource {
  MockScheduleRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i7.ScheduleModel> bookSchedule(
    _i7.ScheduleModel? params,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookSchedule,
          [
            params,
            token,
          ],
        ),
        returnValue: _i10.Future<_i7.ScheduleModel>.value(_FakeScheduleModel_5(
          this,
          Invocation.method(
            #bookSchedule,
            [
              params,
              token,
            ],
          ),
        )),
      ) as _i10.Future<_i7.ScheduleModel>);

  @override
  _i10.Future<_i7.ScheduleModel> updateSchedule(
    _i7.ScheduleModel? params,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [
            params,
            token,
          ],
        ),
        returnValue: _i10.Future<_i7.ScheduleModel>.value(_FakeScheduleModel_5(
          this,
          Invocation.method(
            #updateSchedule,
            [
              params,
              token,
            ],
          ),
        )),
      ) as _i10.Future<_i7.ScheduleModel>);

  @override
  _i10.Future<List<_i7.ScheduleModel>> getSchedulesInfo(
    _i7.ScheduleModel? params,
    String? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSchedulesInfo,
          [
            params,
            userId,
            token,
          ],
        ),
        returnValue:
            _i10.Future<List<_i7.ScheduleModel>>.value(<_i7.ScheduleModel>[]),
      ) as _i10.Future<List<_i7.ScheduleModel>>);
}

/// A class which mocks [DriverRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverRepository extends _i1.Mock implements _i33.DriverRepository {
  MockDriverRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i34.Driver>> getDriversByServiceId(String? serviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriversByServiceId,
          [serviceId],
        ),
        returnValue: _i10.Future<List<_i34.Driver>>.value(<_i34.Driver>[]),
      ) as _i10.Future<List<_i34.Driver>>);

  @override
  _i10.Future<_i34.Driver?> getDriverById(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriverById,
          [driverId],
        ),
        returnValue: _i10.Future<_i34.Driver?>.value(),
      ) as _i10.Future<_i34.Driver?>);
}

/// A class which mocks [DriverRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverRemoteDataSource extends _i1.Mock
    implements _i35.DriverRemoteDataSource {
  MockDriverRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i36.DriverModel>> getDriversByServiceId(
          String? serviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriversByServiceId,
          [serviceId],
        ),
        returnValue:
            _i10.Future<List<_i36.DriverModel>>.value(<_i36.DriverModel>[]),
      ) as _i10.Future<List<_i36.DriverModel>>);

  @override
  _i10.Future<_i36.DriverModel?> getDriverById(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriverById,
          [driverId],
        ),
        returnValue: _i10.Future<_i36.DriverModel?>.value(),
      ) as _i10.Future<_i36.DriverModel?>);
}

/// A class which mocks [RatingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingRepository extends _i1.Mock implements _i37.RatingRepository {
  MockRatingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> addRating(_i38.Rating? rating) => (super.noSuchMethod(
        Invocation.method(
          #addRating,
          [rating],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i38.Rating>> getRatingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRatingsByUser,
          [userId],
        ),
        returnValue: _i10.Future<List<_i38.Rating>>.value(<_i38.Rating>[]),
      ) as _i10.Future<List<_i38.Rating>>);
}

/// A class which mocks [RatingRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingRemoteDataSource extends _i1.Mock
    implements _i39.RatingRemoteDataSource {
  MockRatingRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> addRating(_i40.RatingModel? rating) => (super.noSuchMethod(
        Invocation.method(
          #addRating,
          [rating],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i40.RatingModel>> getRatingsByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRatingsByUser,
          [userId],
        ),
        returnValue:
            _i10.Future<List<_i40.RatingModel>>.value(<_i40.RatingModel>[]),
      ) as _i10.Future<List<_i40.RatingModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i8.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i8.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i10.Future<_i8.Response>.value(_FakeResponse_6(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response>);

  @override
  _i10.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<String>.value(_i22.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i42.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i10.Future<_i42.Uint8List>.value(_i42.Uint8List(0)),
      ) as _i10.Future<_i42.Uint8List>);

  @override
  _i10.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i10.Future<_i8.StreamedResponse>.value(_FakeStreamedResponse_7(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i10.Future<_i8.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
